CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
PROTEIN_SEQUENCE_TOKEN_INDEX = -200
DEFAULT_PROTEIN_SEQUENCE_TOKEN = "<protein_sequence>"
DEFAULT_PROTEIN_SEGMENT_TOKEN = "<prot_segment>"
DEFAULT_PROT_START_TOKEN = "<prot_start>"
DEFAULT_PROT_END_TOKEN = "<prot_end>"
PROTEIN_PLACEHOLDER = "<protein-placeholder>"
VALID_AMINO_ACIDS = set("ACDEFGHIKLMNPQRSTVWY")
